[package]
name = "qvac-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
# This points to your local mock folder
qvac-sdk = { path = "../qvac-mock-sdk" }

image = "0.25"
ort = "=2.0.0-rc.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
